/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Zaposleni;
import java.awt.BorderLayout;
import javax.swing.JDialog;

/**
 *
 * @author Milos
 */
public class FrmGlavna extends javax.swing.JFrame {
    private Zaposleni ulogovaniZaposleni;
    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUlogovaniZaposleni = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuKorisnici = new javax.swing.JMenu();
        jMenuItemUnosNovogKorisnika = new javax.swing.JMenuItem();
        jMenuItemIzmenaPodatakaOKorisniku = new javax.swing.JMenuItem();
        jMenuItemBrisanjeKorisnika = new javax.swing.JMenuItem();
        jMenuItemPretragaKorisnika = new javax.swing.JMenuItem();
        jMenuUsluge = new javax.swing.JMenu();
        jMenuItemUnosUsluge = new javax.swing.JMenuItem();
        jMenuItemBrisanjeUsluge = new javax.swing.JMenuItem();
        jMenuItemPromenaPostojeceUsluge = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelUlogovaniZaposleni.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUlogovaniZaposleni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUlogovaniZaposleni.setText("Ulogovani zaposleni: ");

        jMenuKorisnici.setText("Korisnici");

        jMenuItemUnosNovogKorisnika.setText("Unos novog korisnika");
        jMenuItemUnosNovogKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosNovogKorisnikaActionPerformed(evt);
            }
        });
        jMenuKorisnici.add(jMenuItemUnosNovogKorisnika);

        jMenuItemIzmenaPodatakaOKorisniku.setText("Izmena podataka o korisniku");
        jMenuItemIzmenaPodatakaOKorisniku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIzmenaPodatakaOKorisnikuActionPerformed(evt);
            }
        });
        jMenuKorisnici.add(jMenuItemIzmenaPodatakaOKorisniku);

        jMenuItemBrisanjeKorisnika.setText("Brisanje Korisnika");
        jMenuItemBrisanjeKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBrisanjeKorisnikaActionPerformed(evt);
            }
        });
        jMenuKorisnici.add(jMenuItemBrisanjeKorisnika);

        jMenuItemPretragaKorisnika.setText("Pretraga Korisnika");
        jMenuItemPretragaKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretragaKorisnikaActionPerformed(evt);
            }
        });
        jMenuKorisnici.add(jMenuItemPretragaKorisnika);

        jMenuBar1.add(jMenuKorisnici);

        jMenuUsluge.setText("Usluge");

        jMenuItemUnosUsluge.setText("Unos usluge");
        jMenuItemUnosUsluge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosUslugeActionPerformed(evt);
            }
        });
        jMenuUsluge.add(jMenuItemUnosUsluge);

        jMenuItemBrisanjeUsluge.setText("Brisanje usluge");
        jMenuItemBrisanjeUsluge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBrisanjeUslugeActionPerformed(evt);
            }
        });
        jMenuUsluge.add(jMenuItemBrisanjeUsluge);

        jMenuItemPromenaPostojeceUsluge.setText("Promena postojece usluge");
        jMenuItemPromenaPostojeceUsluge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPromenaPostojeceUslugeActionPerformed(evt);
            }
        });
        jMenuUsluge.add(jMenuItemPromenaPostojeceUsluge);

        jMenuBar1.add(jMenuUsluge);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUlogovaniZaposleni, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUlogovaniZaposleni, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUnosUslugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosUslugeActionPerformed
        FrmUnosUsluge fuu = new FrmUnosUsluge();
        fuu.setUlogovaniZaposleni(ulogovaniZaposleni);
        JDialog d = new JDialog(this, "Unos usluge", true);
        d.setLayout(new BorderLayout());
        d.add(fuu, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemUnosUslugeActionPerformed

    private void jMenuItemBrisanjeUslugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBrisanjeUslugeActionPerformed
        FrmBrisanjeUsluge fbu = new FrmBrisanjeUsluge(false);
        JDialog d = new JDialog(this, "Brisanje usluge", true);
        d.setLayout(new BorderLayout());
        d.add(fbu, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemBrisanjeUslugeActionPerformed

    private void jMenuItemPromenaPostojeceUslugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPromenaPostojeceUslugeActionPerformed
        FrmBrisanjeUsluge fbu = new FrmBrisanjeUsluge(true);
        fbu.setUlogovaniZaposleni(ulogovaniZaposleni);
        JDialog d = new JDialog(this, "Izmena usluge", true);
        d.setLayout(new BorderLayout());
        d.add(fbu, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemPromenaPostojeceUslugeActionPerformed

    private void jMenuItemUnosNovogKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosNovogKorisnikaActionPerformed
        FrmUnosNovogKorisnika funk = new FrmUnosNovogKorisnika();
        funk.setUlogovaniZaposleni(ulogovaniZaposleni);
        JDialog d = new JDialog(this, "Unos novog korisnika", true);
        d.setLayout(new BorderLayout());
        d.add(funk, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemUnosNovogKorisnikaActionPerformed

    private void jMenuItemIzmenaPodatakaOKorisnikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIzmenaPodatakaOKorisnikuActionPerformed
        FrmPretragaKorisnika fpk = new FrmPretragaKorisnika(true, false);
        fpk.setUlogovaniZaposleni(ulogovaniZaposleni);
        JDialog d = new JDialog(this, "Izmena korisnika", true);
        d.setLayout(new BorderLayout());
        d.add(fpk, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemIzmenaPodatakaOKorisnikuActionPerformed

    private void jMenuItemBrisanjeKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBrisanjeKorisnikaActionPerformed
        FrmPretragaKorisnika fpk = new FrmPretragaKorisnika(false, true);
        fpk.setUlogovaniZaposleni(ulogovaniZaposleni);
        JDialog d = new JDialog(this, "Brisanje korisnika", true);
        d.setLayout(new BorderLayout());
        d.add(fpk, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemBrisanjeKorisnikaActionPerformed

    private void jMenuItemPretragaKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretragaKorisnikaActionPerformed
        FrmPretragaKorisnika fpk = new FrmPretragaKorisnika(false, false);
        fpk.setUlogovaniZaposleni(ulogovaniZaposleni);
        JDialog d = new JDialog(this, "Pretraga korisnika", true);
        d.setLayout(new BorderLayout());
        d.add(fpk, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemPretragaKorisnikaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGlavna().setVisible(true);
            }
        });
    }

    public Zaposleni getUlogovaniZaposleni() {
        return ulogovaniZaposleni;
    }

    public void setUlogovaniZaposleni(Zaposleni ulogovaniZaposleni) {
        this.ulogovaniZaposleni = ulogovaniZaposleni;
        String eol = System.getProperty("line.separator");
        jLabelUlogovaniZaposleni.setText("Ulogovani zaposleni: "+ulogovaniZaposleni);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelUlogovaniZaposleni;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemBrisanjeKorisnika;
    private javax.swing.JMenuItem jMenuItemBrisanjeUsluge;
    private javax.swing.JMenuItem jMenuItemIzmenaPodatakaOKorisniku;
    private javax.swing.JMenuItem jMenuItemPretragaKorisnika;
    private javax.swing.JMenuItem jMenuItemPromenaPostojeceUsluge;
    private javax.swing.JMenuItem jMenuItemUnosNovogKorisnika;
    private javax.swing.JMenuItem jMenuItemUnosUsluge;
    private javax.swing.JMenu jMenuKorisnici;
    private javax.swing.JMenu jMenuUsluge;
    // End of variables declaration//GEN-END:variables
}
