/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Korisnik;
import domen.Zaposleni;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import konstante.Operacije;
import konstante.Status;
import modeli.TableModelKorisnici;
import transfer.ObjekatOdgovor;
import transfer.ObjekatZahtev;

/**
 *
 * @author Milos
 */
public class FrmPretragaKorisnika extends javax.swing.JPanel {
    private Zaposleni ulogovaniZaposleni;
    /**
     * Creates new form FrmPretragaKorisnika
     */
    public FrmPretragaKorisnika(boolean izmena, boolean brisanje) {
        initComponents();
        srediTabelu("");
        try {
            jButtonIzbrisi.setVisible(false);
            jButtonIzmeni.setVisible(false);
            if(izmena == true){
                jButtonDetalji.setVisible(false);
                jButtonIzmeni.setVisible(true);
            }
            if(brisanje == true){
                jButtonDetalji.setVisible(false);
                jButtonIzbrisi.setVisible(true);
            }
        } catch (Exception e) {
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFilter = new javax.swing.ButtonGroup();
        jLabelFilter = new javax.swing.JLabel();
        jTextFieldFilter = new javax.swing.JTextField();
        jButtonPronadji = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKorisnici = new javax.swing.JTable();
        jButtonOdustani = new javax.swing.JButton();
        jButtonIzbrisi = new javax.swing.JButton();
        jButtonIzmeni = new javax.swing.JButton();
        jButtonDetalji = new javax.swing.JButton();
        jRadioButtonIme = new javax.swing.JRadioButton();
        jRadioButtonPrezime = new javax.swing.JRadioButton();
        jRadioButtonMesto = new javax.swing.JRadioButton();
        jRadioButtonAdresa = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        jLabelFilter.setText("Filter:");

        jButtonPronadji.setText("Pronadji");
        jButtonPronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPronadjiActionPerformed(evt);
            }
        });

        jTableKorisnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableKorisnici);

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jButtonIzbrisi.setText("Izbriši");
        jButtonIzbrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzbrisiActionPerformed(evt);
            }
        });

        jButtonIzmeni.setText("Izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        jButtonDetalji.setText("Detalji");
        jButtonDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljiActionPerformed(evt);
            }
        });

        buttonGroupFilter.add(jRadioButtonIme);
        jRadioButtonIme.setSelected(true);
        jRadioButtonIme.setText("Ime");

        buttonGroupFilter.add(jRadioButtonPrezime);
        jRadioButtonPrezime.setText("Prezime");

        buttonGroupFilter.add(jRadioButtonMesto);
        jRadioButtonMesto.setText("Mesto");

        buttonGroupFilter.add(jRadioButtonAdresa);
        jRadioButtonAdresa.setText("Adresa");

        jLabel1.setText("Izaberite kriterijum pretrage:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(jLabelFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonIme)
                                        .addGap(55, 55, 55)
                                        .addComponent(jRadioButtonPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jRadioButtonAdresa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButtonMesto)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonPronadji, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldFilter))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDetalji)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonIzbrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOdustani)
                        .addGap(9, 9, 9))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFilter)
                    .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonIme)
                    .addComponent(jRadioButtonPrezime)
                    .addComponent(jRadioButtonMesto)
                    .addComponent(jButtonPronadji)
                    .addComponent(jRadioButtonAdresa)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIzmeni)
                    .addComponent(jButtonDetalji)
                    .addComponent(jButtonIzbrisi)
                    .addComponent(jButtonOdustani))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPronadjiActionPerformed
        String filter = jTextFieldFilter.getText();
        String nalepi = "";
        if(jRadioButtonIme.isSelected()){
            nalepi = " WHERE k.Ime LIKE '"+filter+"%' ORDER BY k.Ime ASC";
        }
        
        if(jRadioButtonPrezime.isSelected()){
            nalepi = " WHERE k.Prezime LIKE '"+filter+"%' ORDER BY k.Prezime ASC";
        }
        
        if(jRadioButtonMesto.isSelected()){
            nalepi = " WHERE m.Naziv LIKE '"+filter+"%' ORDER BY m.Naziv ASC";
        }
        
        if(jRadioButtonAdresa.isSelected()){
            nalepi = " WHERE k.Adresa LIKE '"+filter+"%' ORDER BY k.Adresa ASC";
        }
        
        srediTabelu(nalepi);
        JOptionPane.showMessageDialog(this, "Sistem je našao korisnike po zadatoj vrednosti");        
    }//GEN-LAST:event_jButtonPronadjiActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
        int red = jTableKorisnici.getSelectedRow();
        if(red == -1){
            JOptionPane.showMessageDialog(this, "Morate prvo selektovati korisnika");
            return;
        }
        
        TableModelKorisnici tmk = (TableModelKorisnici) jTableKorisnici.getModel();
        Korisnik k = tmk.vratiSelektovanogKorisnika(red);
        
        ObjekatZahtev zahtev = new ObjekatZahtev(Operacije.PRIKAZI_KORISNIKA, k.getKorisnikID());
        Komunikacija.getInstance().posaljiZahtev(zahtev);
        ObjekatOdgovor odgovor = Komunikacija.getInstance().primiOdgovor();
        
        if(odgovor.getStatus() == Status.ERROR){
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe podatke o izabranom korisnku");
            System.out.println(odgovor.getPoruka());
            return;
        } 
        
        Korisnik kPrikaz = (Korisnik) odgovor.getOdgovor();
        
        this.getTopLevelAncestor().setVisible(false);
        FrmUnosNovogKorisnika funk = new FrmUnosNovogKorisnika(kPrikaz, false);
        funk.setUlogovaniZaposleni(ulogovaniZaposleni);
        JDialog d = new JDialog((JDialog)this.getTopLevelAncestor(), "Izmena korisnika");        
        d.setLayout(new BorderLayout());
        d.add(funk, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);
        JOptionPane.showMessageDialog(this, "Sistem je pronašao podatke o korisniku");
    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jButtonDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljiActionPerformed
        int red = jTableKorisnici.getSelectedRow();
        if(red == -1){
            JOptionPane.showMessageDialog(this, "Morate prvo selektovati korisnika");
            return;
        }
        
        TableModelKorisnici tmk = (TableModelKorisnici) jTableKorisnici.getModel();
        Korisnik k = tmk.vratiSelektovanogKorisnika(red);
        
        if(k == null){
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe podatke o izabranom korisnku");
            return;
        }
        
        this.getTopLevelAncestor().setVisible(false);
        FrmUnosNovogKorisnika funk = new FrmUnosNovogKorisnika(k, true);
        funk.setUlogovaniZaposleni(ulogovaniZaposleni);
        JDialog d = new JDialog((JDialog)this.getTopLevelAncestor(), "Detalji o korisniku");        
        d.setLayout(new BorderLayout());
        d.add(funk, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);
        JOptionPane.showMessageDialog(this, "Sistem je prikazao podatke o korisniku");
    }//GEN-LAST:event_jButtonDetaljiActionPerformed

    private void jButtonIzbrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzbrisiActionPerformed
        int red = jTableKorisnici.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Morate prvo selektovati korisnika");
            return;
        }

        TableModelKorisnici tmk = (TableModelKorisnici) jTableKorisnici.getModel();
        Korisnik k = tmk.vratiSelektovanogKorisnika(red);
        
        ObjekatZahtev zahtev = new ObjekatZahtev(Operacije.IZBRISI_KORISNIKA, k);
        Komunikacija.getInstance().posaljiZahtev(zahtev);
        ObjekatOdgovor odgovor = Komunikacija.getInstance().primiOdgovor();
        
        if(odgovor.getStatus() == Status.ERROR){
            JOptionPane.showMessageDialog(this, "Sistem ne može da izbriše korisnika");
            System.out.println(odgovor.getPoruka());
            return;
        } 

        JOptionPane.showMessageDialog(this, "Sistem je uspešno izbrisao korisnika");
        String filter = jTextFieldFilter.getText();
        srediTabelu(filter);
    }//GEN-LAST:event_jButtonIzbrisiActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        this.getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    public Zaposleni getUlogovaniZaposleni() {
        return ulogovaniZaposleni;
    }

    public void setUlogovaniZaposleni(Zaposleni ulogovaniZaposleni) {
        this.ulogovaniZaposleni = ulogovaniZaposleni;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFilter;
    private javax.swing.JButton jButtonDetalji;
    private javax.swing.JButton jButtonIzbrisi;
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonPronadji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFilter;
    private javax.swing.JRadioButton jRadioButtonAdresa;
    private javax.swing.JRadioButton jRadioButtonIme;
    private javax.swing.JRadioButton jRadioButtonMesto;
    private javax.swing.JRadioButton jRadioButtonPrezime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKorisnici;
    private javax.swing.JTextField jTextFieldFilter;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu(String filter) {
        ObjekatZahtev zahtev = new ObjekatZahtev(Operacije.PRETRAZI_KORISNIKE, filter);
        Komunikacija.getInstance().posaljiZahtev(zahtev);
        ObjekatOdgovor odgovor = Komunikacija.getInstance().primiOdgovor();
        if(odgovor.getStatus() == Status.ERROR){
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe korisnike po zadatoj vrednosti");
            System.out.println(odgovor.getPoruka());
            return;
        }  
        List<Korisnik> lk = (List<Korisnik>) odgovor.getOdgovor();

        TableModelKorisnici tmk = new TableModelKorisnici(lk);
        jTableKorisnici.setModel(tmk);
    }
}
